// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpaxhfoyaytpmcqlwrfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwYXhoZm95YXl0cG1jcWx3cmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzY0MDYsImV4cCI6MjA2Mjk1MjQwNn0.MBunPj_eIgkucH5ePrX8viWALYcVxMn3_5l25bHxLSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);